add Eask linting test

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -22,21 +22,10 @@ jobs:
           - release-snapshot
     steps:
       - name: Get repo to access in conteiner
-        uses: actions/checkout@v6
+        uses: actions/checkout@v4
         with:
           fetch-depth: 1
 
-      - name: Set up Python 3.12
-        uses: actions/setup-python@v5
-        with:
-          python-version: 3.12
-
-      - name: Install melpazoid
-        run: |
-          python -m pip install --upgrade pip
-          # sudo apt-get install emacs-nox && emacs --version
-          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
-          pip install ~/melpazoid
       - name: Install Emacs
         uses: purcell/setup-emacs@master
         with:
@@ -50,6 +39,49 @@ jobs:
          emacs -Q --batch --no-site-file -l org-history-debug.el -l org-history-outline.el -l org-history.el -l org-history-outline-test.el -f ert-run-tests-batch-and-exit
 
 
+      - name: Install package-lint (Emacs)
+        run: |
+          emacs -Q --batch \
+            --eval "(progn \
+                    (require 'package) \
+                    (add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t) \
+                    (package-initialize) \
+                    (unless (package-installed-p 'package-lint) \
+                      (progn \
+                        (package-refresh-contents) \
+                        (package-install 'package-lint))))"
+
+      - name: Install Eask
+        uses: emacs-eask/setup-eask@master
+        with:
+          version: 'snapshot'
+
+      - name: Run Checkdoc
+        run: |
+          echo -e "Eask: Run checkdoc.."
+          eask --strict lint checkdoc -g 2>&1
+
+      - name: Run lint
+        run: |
+          echo -e "Eask: Run package-lint.."
+          eask -g --verbose 5 --strict --allow-error lint package 2>&1 |& tee output.log # always exit with 1 error code
+          if grep -q '[0-9] issue found:' output.log ; then
+            echo "Error detected, failing workflow" ; exit 1
+          fi
+
+      - name: Set up Python 3.12 for melpazoid
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.12
+
+      - name: Install melpazoid
+        run: |
+          python -m pip install --upgrade pip
+          # sudo apt-get install emacs-nox && emacs --version
+          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
+          pip install ~/melpazoid
+
+
       - name: Run
         env:
           LOCAL_REPO: ${{ github.workspace }}
@@ -60,7 +92,8 @@ jobs:
         run: |
           echo $GITHUB_REF
           make -C ~/melpazoid |& tee output.log
-          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+          make_exit=${PIPESTATUS[0]}
+          [ $make_exit -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
           if grep -q "Warning" output.log ; then
             echo "Warnings detected, failing workflow" ; exit 1
           fi
